### ISSUE TITLE
Unable to output image

### ISSUE THREAD

**Issue by DuncanLewis** [szajbus/uploadpack#35]
Hey there,

Having some issues integrating the upload pack. Everything works successfully apart from when I come to output the uploaded file. 

The issue is the way my database is setup, I have a separate table for user details. I save the avatar file name to this table when it is uploaded. 

As you can see my array is slightly different to what is expected as outlined on the docs.

$user array: 

```
 [UserDetail] => Array
        (
            [User] => Array
                (
                    [avatar_file_name] => my_avatar.jpg
                )

        )
```

I've tried using this: 

``` PHP
$this->Upload->uploadUrl($user, 'UserDetail.avatar');
```

But that gives the following error: 

```
Undefined index: UserDetail [APP/Plugin/upload_pack/Model/Behavior/UploadBehavior.php, line 217]
```

Any ideas how I would implement this correctly would be greatly appreciated.

Thanks,
Duncan

**Comment by DuncanLewis** [comment]
Any update here? 😆  /s

**Comment by szajbus** [comment]
Hi @DuncanLewis, apologies for late reply, I hope you found a workaround in the meantime 😉 

I'm afraid the lib only supports flat arrays at the moment, but it probably shouldn't be that difficult to add support for nested ones if someone tried. Contributions are welcome!
