### ISSUE TITLE
Hi, testing ok in CakePHP 2.7..?

### ISSUE THREAD

**Issue by EOM** [szajbus/uploadpack#42]
Hi, one question, testing ok in CakePHP 2.7..?
They provide support for this version ..?
It is also compatible with CakePHP 3.x ..?

**Comment by szajbus** [comment]
@EOM Honestly I have no idea as I am not using CakePHP anymore. Just maintaining this plugin by reviewing and merging commits :)

If you'd like to test it yourself and provide this information to others, that would be very appreciated!

**Comment by EOM** [comment]
Ok, I will try with *CakePHP 2.7*
