### ISSUE TITLE
Please create a composer.json

### ISSUE THREAD

**Issue by yang-wei** [szajbus/uploadpack#43]

**Comment by szajbus** [comment]
@yang-wei To be honest, I'm not fully familiar with composer, but I gave it a shot. Can you take a look? https://github.com/szajbus/uploadpack/pull/44

**Comment by yang-wei** [comment]
hi thanks for you quick response. It would be really helpful to add version into it too =)

Thank you for the package =)

**Comment by szajbus** [comment]
Fixed, thanks.
